<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMoxeQ2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMoxeQ2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMoxeQ2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMoxeQ2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMoxeQ2\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMoxeQ2',
    'container.build_id' => 'd268fb78',
    'container.build_time' => 1706030466,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMoxeQ2');
